# Generated by Django 5.1.1 on 2024-09-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_product_image_product_is_active_product_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
