# Generated by Django 5.1.1 on 2024-09-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_product_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, null=True, unique=True, verbose_name='عنوان در url'),
        ),
    ]
