# Generated by Django 5.1.1 on 2024-09-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_product_description_product_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
