# Generated by Django 5.1.1 on 2024-09-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, null=True, unique=True, verbose_name='عنوان در url'),
        ),
    ]
