# Generated by Django 5.1.1 on 2024-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_index=True, max_length=500, null=True, verbose_name='توضیحات اصلی'),
        ),
    ]
