# Generated by Django 5.1.1 on 2024-10-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.BooleanField(default=False, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='توضیحات اصلی'),
        ),
    ]
