# Generated by Django 5.1.1 on 2025-01-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_alter_product_is_active_alter_product_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='success',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
    ]
