# Generated by Django 5.1.1 on 2024-10-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=100, verbose_name='عنوان اول')),
                ('image_1', models.ImageField(upload_to='images/about_us', verbose_name='تصویر اول')),
                ('description_1', models.TextField(verbose_name='توضیحات اول')),
                ('title_2', models.CharField(max_length=100, verbose_name='عنوان دوم')),
                ('image_2', models.ImageField(upload_to='images/about_us', verbose_name='تصویر دوم')),
                ('description_2', models.TextField(verbose_name='توضیحات دوم')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
