# Generated by Django 5.1.1 on 2024-10-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0002_aboutus_home_description_aboutus_home_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='tag_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تگ 2'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='tag_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تگ 3'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='tag_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تگ 4'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='tag_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تگ 5'),
        ),
    ]
