# Generated by Django 5.1.1 on 2024-09-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=100, verbose_name='شماره تماس')),
                ('email', models.CharField(max_length=100, verbose_name='آدرس ایمیل')),
                ('instagram', models.CharField(max_length=100, verbose_name='صفحه اینستاگرام')),
                ('telegram', models.CharField(max_length=100, verbose_name='آیدی تلگرام')),
                ('whatsapp', models.CharField(max_length=100, verbose_name='شماره واتساپ')),
                ('copy_right', models.CharField(max_length=100, verbose_name='متن کپی رایت')),
                ('time_working', models.CharField(max_length=100, verbose_name='ساعات کاری')),
            ],
            options={
                'verbose_name': 'اطلاعات سایت',
                'verbose_name_plural': 'اطلاعات',
            },
        ),
    ]
