# Generated by Django 5.1.1 on 2024-09-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'اطلاعات سایت', 'verbose_name_plural': 'اطلاعات سایت'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo', verbose_name='لوگو سایت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copy_right',
            field=models.TextField(verbose_name='متن کپی رایت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صفحه اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.IntegerField(max_length=100, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آیدی تلگرام'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='time_working',
            field=models.TextField(max_length=100, verbose_name='ساعات کاری'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره واتساپ'),
        ),
    ]
