# Generated by Django 5.1.1 on 2024-09-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_alter_sitesettings_options_sitesettings_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='شماره واتساپ'),
        ),
    ]
