# Generated by Django 5.1.1 on 2024-09-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_alter_sitesettings_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.IntegerField(verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره واتساپ'),
        ),
    ]
