# Generated by Django 5.1.1 on 2024-10-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_sitesettings_is_main_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='سوال')),
                ('answer', models.CharField(max_length=200, verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'سوالات',
                'verbose_name_plural': 'سوالات',
            },
        ),
    ]
