# Generated by Django 5.1.1 on 2024-10-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_sitequestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitequestions',
            name='answer',
            field=models.TextField(max_length=200, verbose_name='پاسخ'),
        ),
    ]
