# Generated by Django 5.1.1 on 2024-10-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_alter_sitequestions_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitequestions',
            name='answer',
            field=models.TextField(verbose_name='پاسخ'),
        ),
    ]
