# Generated by Django 5.1.1 on 2024-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_alter_sitequestions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequestions',
            name='url_title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name=''),
        ),
    ]
