# Generated by Django 5.1.1 on 2024-10-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0010_sitecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecertificate',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
