# Generated by Django 5.1.1 on 2024-10-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0011_sitecertificate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('image', models.ImageField(upload_to='images/team_profile', verbose_name='تصویر پروفایل')),
                ('job', models.CharField(max_length=200, verbose_name='شغل')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='آیدی اینستاگرام')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='آیدی توییتر')),
            ],
            options={
                'verbose_name': 'اعضائ تیم',
                'verbose_name_plural': 'اعضائ تیم',
            },
        ),
    ]
