# Generated by Django 5.1.1 on 2024-10-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0012_siteteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteteam',
            name='telegram_app',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آیدی تلگرام'),
        ),
        migrations.AddField(
            model_name='siteteam',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره واتساپ'),
        ),
    ]
