# Generated by Django 5.1.1 on 2024-10-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0013_siteteam_telegram_app_siteteam_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteteam',
            name='short_description',
            field=models.TextField(default='', verbose_name='توضیحات کوتاه'),
        ),
    ]
