# Generated by Django 5.1.1 on 2024-11-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0015_remove_siteteam_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_cart',
            field=models.ImageField(blank=True, null=True, upload_to='images/bank_cart', verbose_name='کارت بانکی'),
        ),
    ]
