# Generated by Django 5.1.1 on 2024-10-13 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='')),
                ('url_title', models.CharField(db_index=True, max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(verbose_name='')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('url_title', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده / حذف نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('short_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات کوتاه')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, null=True, unique=True, verbose_name='عنوان در url')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('description2', models.TextField(verbose_name='توضیحات دوم')),
                ('image', models.ImageField(upload_to='images/service_image', verbose_name='تصویر')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/service_image', verbose_name='آیکون')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.servicebrand', verbose_name='')),
                ('category', models.ManyToManyField(related_name='service_categories', to='service_module.servicecategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
