# Generated by Django 5.1.1 on 2024-10-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceBrand',
            new_name='ServiceTags',
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='url_title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='عنوان در url'),
        ),
    ]
