# Generated by Django 5.1.1 on 2024-10-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_module', '0002_rename_servicebrand_servicetags_alter_service_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.servicetags', verbose_name='تگ ها'),
        ),
    ]
