# Generated by Django 5.1.1 on 2024-10-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_module', '0003_alter_service_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetags',
            name='is_active',
            field=models.BooleanField(verbose_name='فعال / غیرفعال'),
        ),
        migrations.AlterField(
            model_name='servicetags',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='servicetags',
            name='url_title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='عنوان در url'),
        ),
    ]
