# Generated by Django 5.1.1 on 2024-10-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_module', '0004_alter_servicetags_is_active_alter_servicetags_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AlterField(
            model_name='servicetags',
            name='is_active',
            field=models.BooleanField(verbose_name='فعال'),
        ),
    ]
