# Generated by Django 5.1.1 on 2024-10-03 10:58

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_read_by_admin',
            field=models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ پیام'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='shamsi_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ شمسی'),
        ),
    ]
