# Generated by Django 5.1.1 on 2024-10-03 10:59

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_module', '0002_contactus_is_read_by_admin_contactus_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='shamsi_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ شمسی'),
        ),
    ]
