# Generated by Django 5.1.1 on 2024-10-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_alter_article_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.articletags', verbose_name='تگ'),
        ),
    ]
