# Generated by Django 5.1.1 on 2025-01-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_articlecategory_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
