# Generated by Django 5.1.1 on 2025-01-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_articlecomment_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='success',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
    ]
